name: CI/CD → GCR & GitOps

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  BACKEND_IMG: gcr.io/${{ secrets.GKE_PROJECT }}/chat-backend
  FRONTEND_IMG: gcr.io/${{ secrets.GKE_PROJECT }}/chat-frontend

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GKE_PROJECT }}
          service_account_key: ${{ secrets.GKE_SA_KEY }}

      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker

      - name: Build & Push Backend Image
        run: |
          docker build -t $BACKEND_IMG:${{ github.sha }} ./backend
          docker push $BACKEND_IMG:${{ github.sha }}

      - name: Build & Push Frontend Image
        run: |
          docker build -t $FRONTEND_IMG:${{ github.sha }} ./frontend
          docker push $FRONTEND_IMG:${{ github.sha }}

      - name: Update Helm chart image tags
        run: |
          yq -i '.backend.tag = strenv(GITHUB_SHA)' charts/chat-app/values.yaml
          yq -i '.frontend.tag = strenv(GITHUB_SHA)' charts/chat-app/values.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add charts/chat-app/values.yaml
          git commit -m "ci: bump image tags to ${{ github.sha }}"
          git push
