apiVersion: v1
kind: Service
metadata:
  name: chat-frontend
spec:
  type: LoadBalancer
  selector:
    app: chat-frontend
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
